<a href="https://colab.research.google.com/github/jaekyung0809/DALC_Scala/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [6]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기# 넘파이 패키지를 불러오기 np로 줄여쓰기
import numpy as np

## array 정의 및 생성

In [47]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기
a  = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:
ndarray = np.arange(10)
print(ndarray)

[0 1 2 3 4 5 6 7 8 9]


## 배열 구성

In [32]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기
b=np.full((3,4),2.71)
print(ar2)

[[2.71 2.71 2.71 2.71]
 [2.71 2.71 2.71 2.71]
 [2.71 2.71 2.71 2.71]]


In [33]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기
c = np.arange(0,11,2)
print(ar3)

[ 0  2  4  6  8 10]


In [18]:
# linespace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하
d = np.linspace(0,1,4)
print(d)

[0.         0.33333333 0.66666667 1.        ]


In [30]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기
ran= np.random.randint(0,100,size=(2,2))
print(ran)

[[78 50]
 [47 31]]


## 배열 인덱싱

In [37]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기
print(a[2],a[-3])

3 8


In [49]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
a[3:9]

array([4, 5, 6, 7, 8, 9])

## 배열 재구조화

In [58]:
#차원의 개수 알아보는 함수
a.ndim

1

In [62]:
#차원의 크기 알아보는 함수
a.shape

(10,)

In [63]:
#전체 배열크기 알아보는 함수
a.size

10

In [65]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성
x=np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [67]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성
x[:5]

array([0, 1, 2, 3, 4])

In [68]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성
x[5:]

array([5, 6, 7, 8, 9])

In [93]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)
arr =  np.array([[0,1],[0,1,2]])
print(arr)

[list([0, 1]) list([0, 1, 2])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [102]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)
xx= np.arange(1,10)
xx1= xx.reshape(3,3)
print(xx1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 배열 결합

In [ ]:
#두개의 배열 결합하기

In [ ]:
#수직으로 두개의 배열 결합하기
#Vstack

In [ ]:
#수평으로 두개의 배열 결합하기
#hstck

## 배열 분할

In [89]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기
x = np.array([1,2,3,4,5,6,7])
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7]


In [106]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
xx2= np.arange(1,17)
xx3= xx2.reshape(4,4)
upper,lower=np.vsplit(xx3,[2])
print(upper,lower)

[[1 2 3 4]
 [5 6 7 8]] [[ 9 10 11 12]
 [13 14 15 16]]


# Numpy 심화

## 유니버셜함수

In [107]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
a.shape

(3, 4)

In [111]:
a.ndim # len(a.shape)와 같습니다

2

In [112]:
a.size

12

In [113]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

array([[4.64575478e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [114]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [ ]:
# x = np.array([-10, -5, 0, 3, 7])
# x에 있는 배열을 모두 양의 정수로 반환하기

In [ ]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기

## 집계함수

In [115]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
힌트: "np.absolute(x)"
print(np.absolute(x))

[2 1 0 1 2]


In [117]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
print(" 코사인 함수 =", "cos")
print("탐젠트 함수= ", "tan") 



theta= [0.         1.57079633 3.14159265]
 코사인 함수 = cos
탐젠트 함수=  tan


In [118]:
#역삼각함수
print("역 사인함수=","arcsin")
print("역 코사인함수=","arccos")
print("역 탄젠트함수=","arctan")

역 사인함수= arcsin
역 코사인함수= arccos
역 탄젠트함수= arctan


In [119]:
#로그함수
x=[1,2,4,10]
print("자연로그=","exp")
print("밑이2인 로그함수=","log2")
print("밑이 10인 로그함수=","log10")

자연로그= exp
밑이2인 로그함수= log2
밑이 10인 로그함수= log10


In [120]:
#지수함수
x=[1,2,3]
print("e^x=","exp(x)")
print("2^x","exp2(x)")
print("3^x=","exp3(x)")

e^x= exp(x)
2^x exp2(x)
3^x= exp3(x)


In [121]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
"np.multiply(x,10,out=y)"
print(y)

[1.e-323 5.e-324 0.e+000 5.e-324 1.e-323]


In [122]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
"np.power(2,x,out=y[::2])"
print(y)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323
 4.0e-323 4.4e-323]


In [123]:
#reduce 함수
x=np.arange(1,5)
"np.add.reduce(x)"

'np.add.reduce(x)'

In [124]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=","np.min(s)")
print("s의최댓값=","np.max(s)")


s의최솟값= np.min(s)
s의최댓값= np.max(s)


In [125]:
#axis 인자
"axis=0: 열기준 집계연산"
"axis=1: 행기준 집계연산"
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"

'axis=none: 배열 내 모든 요소의 집계연산axis 인자'

In [126]:
m= np.random.random((3,4))
print(m)

[[0.62178893 0.9184394  0.92138359 0.77855607]
 [0.24979264 0.21984858 0.6148996  0.66516016]
 [0.74597658 0.04165035 0.68873255 0.69569308]]


## 브로드캐스팅 연산

In [127]:
# 크기가 같은 어레이의 연산을 하기
XX = np.array([0,1,2])
MM = np.ones((3,3))
XX + MM

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [129]:
# 배열의 크기를 늘려서 연산하기
XX1 = np.array([0,1,2,3])
MM2 = np.ones((4,4))
XX1 + MM2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## 비교연산자

In [131]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기
print(any([False,True]))

True


In [135]:
# all함수를 이용하여 true산출 코드 만들기
print(all([True,True]))

True


In [148]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기
ran1= np.random.randint(1,5,2)
print(1 in ran1,"random:",ran1)

False random: [2 2]


## 팬시 인덱싱

In [154]:
#배열을 생성하여 인덱싱하기
index1=np.arange(10)

In [153]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱
index2=np.array([[3,6,9],[2,4,8]])
print(index2)

[[3 6 9]
 [2 4 8]]


## 정렬 

In [158]:
#np.sort함수를 이용하여 복사하기
copy1 = np.array([3,4,5,2,1,8,6])
copy2 = np.sort(copy1)
print(copy2)

[1 2 3 4 5 6 8]


In [ ]:
#변수.sort함수를 이용하여 정렬하기
copy1 = np.array([3,4,5,2,1,8,6])
copy2 = np.sort(copy1)

In [160]:
#np.arsort함수 이용하여 정렬 요소의 인덱스를 반환하기
np.argsort(copy1)

array([4, 3, 0, 1, 2, 6, 5])

In [176]:
#x_reverse를 이용하여 내림차순

In [ ]:
#axis를 이용하여 각 열을 기준으로 정렬하기

In [ ]:
#axis를 이용하여 각 행을 기준으로 정렬하기#axis를 이용하여 각 행을 기준으로 정렬하기